# Generated by Django 5.2.8 on 2025-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_category_comment_article_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_agree",
            field=models.BooleanField(
                default=False, verbose_name="agree to send comment"
            ),
        ),
    ]
