# Generated by Django 5.2.8 on 2025-11-14 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_comment_is_agree"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="App.article",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=50),
        ),
    ]
